/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroemail;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sun.security.rsa.RSACore;
/**
 *
 * @author ariel
 */
public class MainCadastro extends javax.swing.JFrame {

    /**
     * Creates new form MainCadastro
     */
    private CadastroEmail db = new CadastroEmail();
    
    private ResultSet resultSet;
    private String Categoria = "TODOS", Pessoa;
    private List<Integer> IdPessoa = new ArrayList();
    private List<Integer> IdCategoria = new ArrayList();
    private List<Integer> IdEmail = new ArrayList();
    private int IdCategoriaInt;
    private boolean NovoValor;
    
    //Models
    DefaultListModel modelCategoria = new DefaultListModel();
    DefaultListModel modelPessoa = new DefaultListModel();
    
    ComboBoxModel<String> modelCategoriaComboBox;
    ComboBoxModel<String> modelEmailComboBox;
    //private int qtdCategoria, qtdPessoa; Variáveis não serão mais utilizadas
    
    public MainCadastro() {
        initComponents();
        
        
        db.SetConexao();
        db.SetCategoria(Categoria);
        
        ExibirCategorias();
        //ExibirPessoas();
        ExibirBotoes(false);
        cmb_email.setEditable(true);
        //cmb_email.setSelectedIndex(0);
        
        /*TODO List:
        * Necessário pensar em uma maneira de mostrar apenas as pessoas que sejam
        * da categoria selecionada;
        * SELECT p.nome from pessoa as p, email as e, categoria as c WHERE p.id = e.idPessoa and c.id = e.idCategoria and c.descricao = ?
        *
        * #### OK ####
        *
        * Ainda é preciso editar os valores dos contatos e removê-los
        * Verificar se Categoria não é nula antes de inserir
        * 
        * Mostrar pessoas com mais de um email, mesmo que em mesma categoria - talvez utilizando JOIN
        */
       
    }
    
    private void ExibirCategorias(){
        try {
            lst_categorias.removeAll();
            modelCategoria.addElement("TODOS");
            resultSet = db.GetCategoriasRS();
            cmb_descricao.removeAllItems();
            cmb_descricao.addItem("");
            do {                
                modelCategoria.addElement(resultSet.getString(1));
                cmb_descricao.addItem(resultSet.getString(1));
                IdCategoria.add(resultSet.getInt(2));
            } while (resultSet.next());
            
            lst_categorias.setModel(modelCategoria);
        } catch (Exception e) {
            ExceptionShow(e);
        }
        
    }
    
    private void ExibirPessoas(){
        try {
            resultSet = db.GetPessoasRS();
            if (resultSet == null){
                MessageShow("Categoria vazia!");
            } else{
                lst_nomes.removeAll();
                resultSet.first();
                do {                
                    modelPessoa.addElement(resultSet.getString(1));
                    IdPessoa.add(resultSet.getInt(2));
                } while (resultSet.next());
            }
            
            lst_nomes.setModel(modelPessoa);
        }catch(ArrayIndexOutOfBoundsException e){
            modelPessoa.add(0, "");
            ExibirPessoas();
        } 
        catch (Exception e) {
            ExceptionShow(e);
        }
    }
    
    private void ExibirBotoes(boolean visivel){
        lbl_campo1.setVisible(visivel);
        lbl_campo2.setVisible(visivel);
        lbl_campo3.setVisible(visivel);
        
        txt_nome.setVisible(visivel);
        cmb_descricao.setVisible(visivel);
        cmb_email.setVisible(visivel);
        
        jSeparator1.setVisible(visivel);
        jSeparator2.setVisible(visivel);
        jSeparator3.setVisible(visivel);
        
        btn_gravar.setVisible(visivel);
        btn_remover.setVisible(visivel);
    }
    
    
    private void ExceptionShow(Exception e){
        JOptionPane.showMessageDialog(this, "Erro: " + e.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void MessageShow(String text){
        JOptionPane.showMessageDialog(this, text, "Mensagem", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_adicionarPessoa = new javax.swing.JButton();
        btn_adicionarCategoria = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        lbl_campo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_campo2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cmb_descricao = new javax.swing.JComboBox<>();
        lbl_campo3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_gravar = new javax.swing.JButton();
        btn_remover = new javax.swing.JButton();
        cmb_email = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_categorias = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_nomes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-contacts-48.png"))); // NOI18N
        jLabel1.setText("Contatos");

        btn_adicionarPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-user-group-woman-man-48.png"))); // NOI18N
        btn_adicionarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarPessoaActionPerformed(evt);
            }
        });

        btn_adicionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-tag-48.png"))); // NOI18N
        btn_adicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_adicionarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adicionarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_adicionarCategoria)
                            .addComponent(btn_adicionarPessoa))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setAutoscrolls(true);

        lbl_campo1.setText("Nome");
        lbl_campo1.setOpaque(true);

        lbl_campo2.setText("Categoria");
        lbl_campo2.setOpaque(true);

        lbl_campo3.setText("E-Mail");
        lbl_campo3.setOpaque(true);

        btn_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-edit-48.png"))); // NOI18N
        btn_gravar.setText("Gravar");
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });

        btn_remover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-clear-symbol-48.png"))); // NOI18N
        btn_remover.setText("Remover");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_campo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_descricao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_campo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_campo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_gravar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_remover)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_campo1)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_campo2)
                    .addComponent(cmb_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_campo3)
                    .addComponent(cmb_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(329, 329, 329))
        );

        lst_categorias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "TODOS" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_categorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_categorias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_categoriasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lst_categorias);

        lst_nomes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_nomes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_nomesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lst_nomes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Adicionar Categoria
    
    //Inicialmente era utilizado um formulário separado para receber o novo nome, agora é utilizado o valor digitado pelo usuário emum JOptionPane 
    private void btn_adicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarCategoriaActionPerformed
        //Adicionar adicionar = new Adicionar(1);
        //adicionar.setVisible(true);
        String valor = JOptionPane.showInputDialog(this,"Adicionar", DISPOSE_ON_CLOSE);
        db.AdicionarCategoria(valor);
        ExibirCategorias();
    }//GEN-LAST:event_btn_adicionarCategoriaActionPerformed

    private void btn_adicionarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarPessoaActionPerformed
        //Adicionar adicionar = new Adicionar(2);
        //adicionar.setVisible(true);
        String valor = JOptionPane.showInputDialog(this,"Adicionar", DISPOSE_ON_CLOSE);
        db.AdicionarPessoa(valor);
        ExibirPessoas();
    }//GEN-LAST:event_btn_adicionarPessoaActionPerformed

    private void lst_nomesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_nomesValueChanged
        //Pessoa = lst_nomes.getSelectedValue();
        int id = IdPessoa.get(lst_nomes.getSelectedIndex());
        int index = db.GetCategoriaInteger();
        db.SetID(id);
        
        try {
            String nome = db.GetNomeString();
            txt_nome.setText(nome); 
            //modelCategoriaComboBox = (ComboBoxModel<String>) modelCategoria;
            //cmb_descricao.setModel(modelCategoriaComboBox);
            cmb_descricao.setSelectedIndex(index);
            cmb_email.removeAllItems();
            IdEmail.clear();
            resultSet = db.GetEmailRS();
            do {                
                cmb_email.addItem(resultSet.getString(1));
                IdEmail.add(resultSet.getInt(2));
            } while (resultSet.next());
            ExibirBotoes(true);
        } catch (SQLException e) {
            ExibirBotoes(true);
            cmb_email.removeAllItems();
        }
        catch (Exception e){
            ExceptionShow(e);
            ExibirBotoes(false);
        }        
    }//GEN-LAST:event_lst_nomesValueChanged

    private void lst_categoriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_categoriasValueChanged
        ExibirBotoes(false);
        Categoria = lst_categorias.getSelectedValue();
        db.SetCategoria(Categoria);
        try {
            modelPessoa.removeAllElements();
        } catch (Exception e) {
        }
        ExibirPessoas();
    }//GEN-LAST:event_lst_categoriasValueChanged

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
        db.SetNome(txt_nome.getText());
        NovoValor = db.SetEmail(cmb_email.getSelectedItem().toString());
        IdCategoriaInt = IdCategoria.get(cmb_descricao.getSelectedIndex()-1); 
        db.SetIDCategoria(IdCategoriaInt);
        if (!NovoValor) {
            int indexEmail = cmb_email.getSelectedIndex();
            db.SetIDEmail(IdEmail.get(indexEmail));
        }
        String msg = db.AlterarValorCadastro();
        MessageShow(msg);

    }//GEN-LAST:event_btn_gravarActionPerformed

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        if (JOptionPane.showConfirmDialog(this,"Deseja realmente remover este contato?", "Remover Permanentemente",DISPOSE_ON_CLOSE) == 0){
            int indexEmail = cmb_email.getSelectedIndex();
            db.SetIDEmail(IdEmail.get(indexEmail));
            db.Remover();
        }
    }//GEN-LAST:event_btn_removerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionarCategoria;
    private javax.swing.JButton btn_adicionarPessoa;
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_remover;
    private javax.swing.JComboBox<String> cmb_descricao;
    private javax.swing.JComboBox<String> cmb_email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_campo1;
    private javax.swing.JLabel lbl_campo2;
    private javax.swing.JLabel lbl_campo3;
    private javax.swing.JList<String> lst_categorias;
    private javax.swing.JList<String> lst_nomes;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
